# How do we handle errors in FASTAPI

# this can be seen when client sends a request with an invalid value or client may not have enough permissions to perform that action
# we can use HTTPException to handle errors

from fastapi import APIRouter, HTTPException

app = APIRouter()

items = {"foo": "The Foo Wrestlers"}


@app.get("/items/{item_id}")
async def read_item(item_id: str):
    if item_id not in items:
        raise HTTPException(status_code=404, detail="Item not found")
    return {"item": items[item_id]}
# in here if we provide input for item as foo then it will work else will display error

# first thing is in query parameters we provide certain conditions like min_length, max_length, etc. the fast api will
# automatically validate it and check if the value is valid or not 
# ex: name is string with below 10 chars => if we provide value as dssssj it will think it is valid and return value
# but only we know what is valid and what is not so we will check whatever the data entered is available in db and then approve them w
# which is status code

# CUSTOM headers are like notes to the error message of 404 or 405 like that 
# instead of just saying item not found we can say item not found in db or something like that

# in general when we provide a wrong value in query or path parameters then fastapi will send an error right
# os that is only REQUEST VALIDATION ERROR it will show like a json format ex: get item
# but we can override the deafult error message byt RVE


# {
#   "detail": [
#     {
#       "loc": ["body", "price"],
#       "msg": "value is not a valid float",
#       "type": "type_error.float"
#     }
#   ]
# }
# instead of showing like above if we show like ur id is not valid or name is not correct easy for udnerstanding


@app.exception_handler(RequestValidationError) # this will say FAST API to use the custom error handler for RequestValidationError
async def custom_validation_exception_handler(request: Request, exc: RequestValidationError): # exc is the obkect and Requestvaliadtion error is real 
                                                                    # error generated by fastapi
    return JSONResponse(
        status_code=422, 
        content={
            "message": "Oops! Something went wrong. Please check your input.",
            "details": exc.errors(),  # This gives the actual error details (optional)
        },)
       # here instead of only displayin fastapi error we are just adding the message like oops something and then followed by fast api error only


